spring:
  datasource:
    sql-script-encoding: UTF-8
    initialization-mode: always
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/project1
      username: sa
      password: password
  h2:
    console:
      enabled: true
      path: /h2_console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: false
    open-in-view: false


  security:
    basic:
      enabled: false # security 기본 인증 옵션 제거
  logging:
    level:
      org.hibernate.type: trace  # JPA로 생성되는 쿼리의 파라미터 값 확인